package simo.mi6.project.tier2.Corba;


/**
* tier2/StringsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tier2.idl
* jeudi 21 juin 2018 14 h 34 CEST
*/

public final class StringsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringsHolder ()
  {
  }

  public StringsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = simo.mi6.project.tier2.Corba.StringsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    simo.mi6.project.tier2.Corba.StringsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return simo.mi6.project.tier2.Corba.StringsHelper.type ();
  }

}
