package simo.mi6.project.tier2.Corba;


/**
* tier2/Tier2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tier2.idl
* jeudi 21 juin 2018 14 h 34 CEST
*/

public interface Tier2 extends Tier2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tier2
