package simo.mi6.project.tier2.Corba;


/**
* tier2/Tier2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tier2.idl
* jeudi 21 juin 2018 14 h 34 CEST
*/

public interface Tier2Operations 
{
  boolean createUser (String username, String password);
  boolean deleteUser (String username);
  boolean userConnexion (String username, String password);
  boolean createNewTweet (String username, String password, String tweet);
  String[] getTweetsForUser (String username);
  boolean startFollowing (String followerUsername, String followedUsername);
  boolean stopFollowing (String followerUsername, String followedUsername);
  String[] searchForUser (String searchUsername);
  String[] searchInTweets (String searchString);
  String[] getAllUsers ();
} // interface Tier2Operations
