package simo.mi6.project.tier2;


/**
* tier2/Tier2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tier2.idl
* jeudi 7 juin 2018 16 h 14 CEST
*/

public interface Tier2 extends Tier2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tier2
